theme = "gruber-darker"

[editor]
gutters = ["diagnostics", "diff"]
auto-completion = false
auto-format = false
popup-border = "all"

[editor.indent-guides]
render = true

[keys.normal]
"C-[" = ["keep_primary_selection", "collapse_selection"]
X = "extend_line_above"

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
