theme = "sunset"

[editor]
gutters      = ["diagnostics", "spacer", "diff"]
bufferline   = "always"
popup-border = "all"
auto-format  = false
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"

[keys.normal]
"C-[" = ["keep_primary_selection", "collapse_selection"]
"C-c" = ["save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard",
         "paste_primary_clipboard_before", "jump_backward"]

[keys.insert]
"C-[" = "normal_mode"
"C-c" = ["normal_mode", "save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard",
         "paste_primary_clipboard_before", "jump_backward", "insert_mode"]

[keys.select]
"C-[" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
"C-c" = "no_op"
