theme = "gruber-darker"

[editor]
gutters = ["diagnostics", "diff"]
auto-completion = false
auto-format = false
popup-border = "all"

[editor.indent-guides]
render = true

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]
"C-l" = ["save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard", "paste_primary_clipboard_before", "jump_backward"]
X = "extend_line_above"

[keys.insert]
"C-c" = "normal_mode"
"C-l" = ["normal_mode", "save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard", "paste_primary_clipboard_before", "jump_backward", "insert_mode"]

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]
