theme = "sunset"

[editor]
gutters = ["diagnostics", "spacer", "diff"]
bufferline = "always"
auto-format = false
popup-border = "all"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
trim-final-newlines = true
trim-trailing-whitespace = true

[keys.normal]
"X" = "extend_line_above"
"C-c" = ["save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard",
         "paste_primary_clipboard_before", "jump_backward"]

[keys.insert]
"C-c" = ["normal_mode", "save_selection", "extend_to_line_bounds", "yank_to_primary_clipboard",
         "paste_primary_clipboard_before", "jump_backward", "insert_mode"]

[keys.select]
"C-c" = ["yank_to_primary_clipboard", "paste_primary_clipboard_before"]
