attribute = "rose"

type = "rose"
"type.enum.variant" = "mud"

constructor = "wood"

constant = "fire"
"constant.character" = "mud"
"constant.character.escape" = "wine"
"constant.numeric"   = "wood"

string = "grass"
"string.regexp"  = "wine"
"string.special" = "peach"
"string.special.symbol" = "sky"

comment = { fg = "cmnt", modifiers = ["italic"] }

variable = "text"
"variable.builtin" = { fg = "sky", modifiers = ["italic"] }
# TODO: variable.parameter
"variable.other.member" = "mud"

label = "sky"

punctuation = "cmnt"
"punctuation.special" = "wine"

keyword = "sun"
"keyword.directive" = "sky"

operator = "wine"

function = "peach"
"function.macro" = "sky"

tag = "peach"

namespace = { fg = "peach", modifiers = ["italic"] }

special = "sky"

# Ui
"ui.background" = { fg = "text", bg = "base" }

"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "attn", modifiers = ["bold"] }

# TODO: ui.debug

"ui.linenr" = "block"
"ui.linenr.selected" = "cmnt"

"ui.statusline" = { bg = "block" }
"ui.statusline.inactive" = { fg = "cmnt" }
"ui.statusline.normal"   = { fg = "block", bg = "fire",  modifiers = ["bold"] }
"ui.statusline.insert"   = { fg = "block", bg = "grass", modifiers = ["bold"] }
"ui.statusline.select"   = { fg = "block", bg = "wine",  modifiers = ["bold"] }

"ui.bufferline" = { fg = "cmnt", bg = "block" }
"ui.bufferline.active" = "sun"

"ui.popup" = { fg = "text", bg = "block" }

"ui.window" = { fg = "block", modifiers = ["bold"] }

"ui.help" = { fg = "text", bg = "block" }

"ui.text" = { fg = "text", bg = "base" }
"ui.text.focus"    = "sun"
"ui.text.inactive" = { fg = "cmnt", modifiers = ["italic"] }
"ui.text.info"     = { bg = "block" }

"ui.virtual" = { fg = "block" }
"ui.virtual.ruler"        = { bg = "block" }
"ui.virtual.indent-guide" = "sel"
"ui.virtual.jump-label"   = { fg = "attn", modifiers = ["bold"] }

"ui.menu" = { fg = "text", bg = "base" }
"ui.menu.selected" = { bg = "sel" }
"ui.menu.scroll"   = "sel"

"ui.selection" = { bg = "sel" }

"ui.highlight" = { bg = "sel" }

error   = "attn"
warning = "sun"
info    = "rose"
hint    = "sky"

"diagnostic.error"   = { underline = { color = "attn", style = "line" } }
"diagnostic.warning" = { underline = { color = "sun",  style = "line" } }
"diagnostic.info"    = { underline = { color = "rose", style = "line" } }
"diagnostic.hint"    = { underline = { color = "sky",  style = "line" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated"  = { modifiers = ["crossed_out"] }

[palette]
# Reddish
fire  = "#EE7711"
rose  = "#EE7777"
peach = "#EEBB77"
wood  = "#997755"

# Bluish
sky  = "#77AAAA"
wine = "#775599"

# Greenish
grass = "#66CC33"
mud   = "#BBCC77"
sun   = "#EEEE11"

# Ui
base  = "#111111"
block = "#222222"
sel   = "#333333"
cmnt  = "#777777"
text  = "#EEEEEE"
attn  = "#EE1111"
